// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2667.Steamworks.commands;
import org.usfirst.frc2667.Steamworks.Robot;
import org.usfirst.frc2667.Steamworks.util.GameFieldVectors;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class AutonomousCommand extends CommandGroup {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public AutonomousCommand() {
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    
    	Robot.driveTrain.setVector(new GameFieldVectors(0, 0));
    	if (Robot.driveTrain.getVector().getStartingPosition() == GameFieldVectors.StartingPosition.FacingAway){
    		this.addSequential(new PlaceGearOnLeftPeg());
    	} else if (Robot.driveTrain.getVector().getStartingPosition() == GameFieldVectors.StartingPosition.FacingTowards){
    		this.addSequential(new PlaceGearOnRightPeg());
    	} else {
    		this.addSequential(new PlaceGearOnMiddlePeg());
    	}
    }
}
